use rand::Rng;
use regex::Regex;
use std::collections::{HashMap, HashSet};

const APERTURE_MIN_ID: u16 = 10;
const APERTURE_MAX_ID: u16 = 8191;

#[derive(Debug, Clone)]
struct AddLine {
    line_index: usize,
    id: u16,
    line: String,
}

#[derive(Debug, Clone, Copy)]
struct TextLayout {
    has_trailing_newline: bool,
    eol: &'static str,
}

pub fn looks_like_easyeda_export(content: &str) -> bool {
    content.contains("EasyEDA Pro")
}

pub fn disguise_as_easyeda(content: &str, layer_name: &str) -> String {
    if looks_like_easyeda_export(content) {
        return content.to_string();
    }

    let (lines, layout) = split_text(content);
    let mut result = Vec::with_capacity(lines.len() + 5);
    let now = chrono::Local::now().format("%Y-%m-%d %H:%M:%S");

    result.push(format!("G04 Layer: {}*", layer_name));
    result.push(format!("G04 EasyEDA Pro v3.2.91, {}*", now));
    result.push("G04 Gerber Generator version 0.3*".to_string());
    result.push("G04 Scale: 100 percent, Rotated: No, Reflected: No*".to_string());
    result.push("G04 Generated by one-click*".to_string());
    result.extend(lines);

    join_text(&result, layout)
}

pub fn apply_lceda_signature(content: &str, imported_mode: bool) -> String {
    let (mut lines, layout) = split_text(content);
    lines = strip_all_unused_adds(&lines);

    let add_lines = collect_add_lines(&lines);
    if add_lines.is_empty() {
        return join_text(&lines, layout);
    }

    let mut rng = rand::thread_rng();
    let pick = 5 + rng.gen_range(0..5);
    let selected = &add_lines[pick.min(add_lines.len() - 1)];
    let selected_id = selected.id;

    let mut shifted = shift_aperture_ids(&lines, selected_id);
    let shifted_text = join_text(&shifted, layout);

    let hash_base = if imported_mode {
        format!("494d{}", shifted_text)
    } else {
        shifted_text
    };
    let pair = md5_pair(&hash_base);

    let signature_line = build_signature_line(&selected.line, selected_id, &pair, &mut rng);
    let insert_at = find_insert_index(&shifted, selected_id);
    shifted.insert(insert_at, signature_line);

    join_text(&shifted, layout)
}

fn split_text(content: &str) -> (Vec<String>, TextLayout) {
    let lines = content.lines().map(|line| line.to_string()).collect();
    let has_trailing_newline = content.ends_with('\n');
    let eol = if content.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    (
        lines,
        TextLayout {
            has_trailing_newline,
            eol,
        },
    )
}

fn join_text(lines: &[String], layout: TextLayout) -> String {
    let mut text = lines.join(layout.eol);
    if layout.has_trailing_newline && !text.is_empty() {
        text.push_str(layout.eol);
    }
    text
}

fn collect_add_lines(lines: &[String]) -> Vec<AddLine> {
    let add_re = Regex::new(r"^%ADD(\d{2,4})\D").expect("valid ADD regex");
    lines
        .iter()
        .enumerate()
        .filter_map(|(index, line)| {
            let cap = add_re.captures(line)?;
            let id = cap.get(1)?.as_str().parse::<u16>().ok()?;
            Some(AddLine {
                line_index: index,
                id,
                line: line.clone(),
            })
        })
        .collect()
}

fn strip_all_unused_adds(lines: &[String]) -> Vec<String> {
    let add_lines = collect_add_lines(lines);
    if add_lines.is_empty() {
        return lines.to_vec();
    }

    let used = collect_used_apertures(lines);
    let remove: HashSet<usize> = add_lines
        .iter()
        .filter(|add| !used.contains(&add.id))
        .map(|add| add.line_index)
        .collect();

    lines
        .iter()
        .enumerate()
        .filter_map(|(idx, line)| (!remove.contains(&idx)).then_some(line.clone()))
        .collect()
}

fn collect_used_apertures(lines: &[String]) -> HashSet<u16> {
    let use_re = Regex::new(r"D(\d{2,4})\*").expect("valid use regex");
    let mut used = HashSet::new();
    for line in lines {
        for cap in use_re.captures_iter(line) {
            if let Ok(id) = cap[1].parse::<u16>() {
                if id >= APERTURE_MIN_ID {
                    used.insert(id);
                }
            }
        }
    }
    used
}

fn shift_aperture_ids(lines: &[String], base_id: u16) -> Vec<String> {
    let mut shifted = Vec::with_capacity(lines.len());
    for line in lines {
        if let Some(new_line) = rewrite_prefixed_id(line, "%ADD", base_id, APERTURE_MIN_ID, false) {
            shifted.push(new_line);
            continue;
        }
        if let Some(new_line) = rewrite_prefixed_id(line, "G54D", base_id, APERTURE_MIN_ID, false) {
            shifted.push(new_line);
            continue;
        }
        if let Some(new_line) = rewrite_prefixed_id(line, "D", base_id, APERTURE_MIN_ID, true) {
            shifted.push(new_line);
            continue;
        }
        shifted.push(line.clone());
    }
    shifted
}

fn rewrite_prefixed_id(
    line: &str,
    prefix: &str,
    base_id: u16,
    min_id: u16,
    require_star_after_id: bool,
) -> Option<String> {
    if !line.starts_with(prefix) {
        return None;
    }
    let rest = &line[prefix.len()..];
    let digits = rest.chars().take_while(|c| c.is_ascii_digit()).count();
    if !(2..=4).contains(&digits) {
        return None;
    }
    let id = rest[..digits].parse::<u16>().ok()?;
    if id < min_id {
        return None;
    }
    let suffix = &rest[digits..];
    if require_star_after_id && !suffix.starts_with('*') {
        return None;
    }

    let new_id = if id >= base_id && id < APERTURE_MAX_ID {
        id + 1
    } else {
        id
    };

    if new_id == id {
        return None;
    }

    Some(format!("{}{}{}", prefix, new_id, suffix))
}

fn md5_pair(input: &str) -> String {
    let digest = md5::compute(input.as_bytes());
    format!("{:02}", digest.0[15] % 100)
}

fn build_signature_line(
    selected_line: &str,
    selected_id: u16,
    pair: &str,
    rng: &mut impl Rng,
) -> String {
    let number_re = Regex::new(r",([\d.]+)").expect("valid number regex");
    let base_line = if number_re.is_match(selected_line) {
        selected_line.to_string()
    } else {
        format!("%ADD{}C,{:.4}*%", selected_id, rng.gen::<f64>())
    };

    number_re
        .replacen(&base_line, 1, |caps: &regex::Captures| {
            let base = caps[1].parse::<f64>().unwrap_or(0.01);
            let mut merged = format!("{:.2}{}", base, pair);
            if merged.parse::<f64>().unwrap_or(0.0) == 0.0 {
                merged = "0.0100".to_string();
            }
            format!(",{}", merged)
        })
        .to_string()
}

fn find_insert_index(lines: &[String], selected_id: u16) -> usize {
    let add_lines = collect_add_lines(lines);
    if add_lines.is_empty() {
        return 0;
    }

    let by_id: HashMap<u16, usize> = add_lines.iter().map(|a| (a.id, a.line_index)).collect();

    if let Some(next_id) = selected_id.checked_add(1) {
        if let Some(next_pos) = by_id.get(&next_id) {
            return *next_pos;
        }
    }

    add_lines
        .iter()
        .max_by_key(|a| a.line_index)
        .map(|a| a.line_index + 1)
        .unwrap_or(0)
}
